test:
  build: .
  links:
    - backend
  command:
    - "bundle"
    - "exec"
    - "rake"
  environment:
    - CODECLIMATE_REPO_TOKEN="xxxxx"

backend:
  image: 3scale/backend:latest
  expose:
    - "3000"
  command:
    - "script/test_external"