config_version = "0"

exclude_patterns = [
  "**/vendor/**",
]

test_patterns = [
  "spec"
]

[[source]]
default = true
name = "default"

[[plugin]]
name = "reek"

[[plugin]]
name = "rubocop"
version = "1.75.2"
