version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7
      - image: redis:6.2-alpine
      - image: quay.io/3scale/apisonator:latest
        environment:
          CONFIG_INTERNAL_API_USER: user
          CONFIG_INTERNAL_API_PASSWORD: password
          CONFIG_QUEUES_MASTER_NAME: redis://localhost:6379
          CONFIG_REDIS_PROXY: redis://localhost:6379
          RACK_ENV: test
        command: 3scale_backend start -p 3000

    steps:
      - checkout

      - run:
          name: bundle install
          command: bundle install

      - run:
          name: Run tests
          environment:
            THREESCALE_CORE_INTERNAL_API: http://user:password@localhost:3000
          command:  bundle exec rake test

workflows:
  version: 2
  workflow:
    jobs:
      - build
