#!/bin/bash
PROJECTNAME=core
MYNAME=$(basename $0)
MYDIR="$(pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
trap "atexit_fn" EXIT

atexit_fn()
{
    popd > /dev/null 2>&1
}

if test $# -lt 2; then
    echo "${MYNAME} <PROJECT> <NAME>" >&2
    exit 1
fi

PROJECT=${1}
NAME=${2}
DOCKER=$(which docker || exit 1)

CID=$(${DOCKER} run -d -p 22 --name ${NAME} ${PROJECT} /usr/sbin/sshd -o AllowAgentForwarding=yes -D)
IPPORT=$(${DOCKER} port "${CID}" 22)
IP=$(echo "${IPPORT}" | cut -d':' -f 1)
PORT=$(echo "${IPPORT}" | cut -d':' -f 2)
chmod 600 "${MYDIR}/docker_key"
ssh root@"${IP}" -p "${PORT}" -i "${MYDIR}/docker_key" -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no -o ForwardAgent=yes \
  "mkdir -p /root/.ssh && /bin/echo -e 'Host *\nStrictHostKeyChecking no\nUserKnownHostsFile /dev/null' > /root/.ssh/config \
  && cd /opt/${PROJECTNAME} \
  && bundle install --jobs `grep -c processor /proc/cpuinfo` \
  && cd /opt/${PROJECTNAME} && script/ci"
RESULT=$?
${DOCKER} rm --force ${NAME}
exit ${RESULT}
