#!/usr/bin/env bash
export CI=jenkins

/usr/bin/redis-server --port 6379 --daemonize yes
echo ThreeScale::Backend.configure { \|c\| c.redis.proxy=\'localhost:6379\' } > ~/.3scale_backend.conf

# report to CodeClimate from Jenkins only
# try to tell Jenkins apart from others
if test "${JENKINS_HOME}x" != "x"; then
    export CODECLIMATE_REPO_TOKEN="xxxxx"
fi

bundle exec rake ci
RESULT=$?

kill -TERM `pidof redis-server`

exit $RESULT
