#!/usr/bin/env bash
export CI=jenkins

/usr/bin/redis-server --port 6379 --daemonize yes
echo ThreeScale::Backend.configure { \|c\| c.redis.proxy=\'localhost:6379\' } > ~/.3scale_backend.conf

# report to CodeClimate from Jenkins only
# try to tell Jenkins apart from others
if test "${1}x" = "jenkinsx"; then
    # we're on jenkins, only set CodeClimate token if on master
    # (note: jenkins detaches HEAD, so must compare commit ids)
    if test "$(git rev-parse HEAD)" = "$(git rev-parse origin/master)"; then
        # CodeClimate test reporter is not able to know that HEAD is master and identify it as such
        # so hack this here -- note: we're already on master, so the only thing this does is resetting
        # the HEAD pointer to origin/master (ie. no actual working copy changes).
        git checkout -q -b master origin/master || git checkout -q master
        export CODECLIMATE_REPO_TOKEN="xxxxx"
    else
        # don't build coverage report on Jenkins, it won't be used by anyone
        export NO_COVERAGE=1
    fi
fi

bundle exec rake ci
RESULT=$?

kill -TERM `pidof redis-server`

exit $RESULT
