#!/usr/bin/env bash

GEMINABOX=$(gem sources --list | grep "localhost")

if [ -z $GEMINABOX ]
then
    gem sources --add 'https://xxxxx:xxxxx@localhost'
fi

GEM=$(gem build 3scale_core.gemspec | grep "File: " | awk '{ print $2 }')
gem inabox $GEM
